[database]
host = "host name"
port = 5432
database = "postgres"
username = "username"
password = "YOUR_ACTUAL_SUPABASE_PASSWORD"

[auth]
redirect_uri = "your-app-name.streamlit.app"
cookie_secret = "your-random-32-char-string-same-as-local"

[google]
client_id = "YOUR_CLIENT_ID.apps.googleusercontent.com"
client_secret = "YOUR_CLIENT_SECRET"

[app]
admin_emails = ["username@gmail.com"]
